language: php

php:
  - "7.0"
  - "5.6"

before_script:
  - travis_retry composer self-update
  - travis_retry composer install -o --no-interaction --prefer-dist

script: vendor/bin/phpunit --color=always
